services:
  pdf_processor_service:
    build:
      context: .
      dockerfile: ./pdf_processor_service/Dockerfile
    container_name: pdf_processor_service
    ports:
      - "8000:8000"
    env_file:
      - ./pdf_processor_service/.env
  
  chat_service:
    build:
      context: .
      dockerfile: ./chat_service/Dockerfile
    container_name: chat_service
    ports:
      - "8001:8000"
    env_file:
      - ./chat_service/.env

  redis:
    container_name: redis
    image: redis:7.4.4-alpine
    expose:
      - "6379"

  embedder_service:
    build:
      context: .
      dockerfile: ./embedder_service/Dockerfile
    container_name: embedder_service
    ports:
      - "8005:8000"
    env_file:
      - ./embedder_service/.env
  
  chromadb:
    container_name: 
    image: 
    expose:
      - "5100"

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Admin UI
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

  createbucket:
    image: minio/mc
    container_name: createbucket
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
        echo 'Waiting for MinIO to be ready...';
        until mc alias set local http://minio:9000 minioadmin minioadmin; do
          sleep 2;
        done;
        echo 'MinIO is healthy, continuing...';
        mc mb -p local/omnifiles;
        mc policy set none local/omnifiles
        exit 0;
      "

volumes:
  minio-data:
