services:
  pdf_processor_service:
    build:
      context: ./pdf_processor_service
    container_name: pdf_processor_service
    environment:
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_BUCKET=omnifiles
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    ports:
      - "8000:8000"
    env_file:
      - ./pdf_processor_service/.env

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Admin UI
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

  createbucket:
    image: minio/mc
    container_name: createbucket
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
        sleep 5;
        mc alias set local http://minio:9000 minioadmin minioadmin;
        mc mb -p local/omnifiles;
        mc policy set public local/omnifiles;
        exit 0;
      "

volumes:
  minio-data: