FROM python:3.13-slim

WORKDIR /app

ENV PYTHONPATH=/app/pdf_extraction:/app/shared_utils

RUN apt-get update && apt-get install -y build-essential && rm -rf /var/lib/apt/lists/*
COPY pdf_extraction/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY shared_utils ./shared_utils
COPY pdf_extraction ./pdf_extraction

EXPOSE 8000

# Start the FastAPI server
CMD ["sh", "-c", "PYTHONPATH=/app/pdf_extraction uvicorn pdf_extraction.main:app --host 0.0.0.0 --port 8000"]
