name: Trivy Scan

on:
  push:
    branches: [dev]
  workflow_dispatch:

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    env:
      TRIVY_EXCLUDE_SERVICES: ${{ secrets.TRIVY_EXCLUDE_SERVICES }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Install Trivy CLI
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: Extract metadata
        id: meta
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV

          git fetch --tags
          LATEST_TAG=$(git tag --list 'v*.*.*' | sort -V | tail -n1)
          FALLBACK_TAG="${LATEST_TAG:-v0.0.0}"
          echo "GIT_TAG=${FALLBACK_TAG}-${SHORT_SHA}" >> $GITHUB_ENV
          echo "REPO_OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Copy example.env to .env
        run: |
          echo "Copying example.env to .env..."
          find . -name "example.env" | while read f; do
            cp "$f" "$(dirname "$f")/.env"
            echo "✓ Created $(dirname "$f")/.env"
          done

      - name: Build all Docker Compose services
        run: |
          echo "Building services from docker-compose.yml..."
          docker compose build

      - name: Run Trivy scan for all services
        run: |
          echo "Running Trivy scans..."
          SERVICES=$(docker compose config --services)

          for SERVICE in $SERVICES; do
            if [[ " $TRIVY_EXCLUDE_SERVICES " =~ " $SERVICE " ]]; then
              echo "Skipping $SERVICE (excluded via secret)"
              continue
            fi

            IMAGE_ID=$(docker images --filter=reference="*${SERVICE}*" --format "{{.ID}}" | head -n1)

            if [[ -z "$IMAGE_ID" ]]; then
              echo "Skipping $SERVICE (no image built)"
              continue
            fi

            echo "Scanning $SERVICE ($IMAGE_ID)..."
            trivy image --exit-code 1 --severity CRITICAL,HIGH --no-progress "$IMAGE_ID"
          done
